export enum PermissionType {
  ROLE_GET = 'ROLE_GET',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',

  FILE_GET = 'FILE_GET',
  FILE_CREATE = 'FILE_CREATE',

  USER_GET = 'USER_GET',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_RESTORE = 'USER_RESTORE',

  DOCUMENT_GET = 'DOCUMENT_GET',
  DOCUMENT_CREATE = 'DOCUMENT_CREATE',
  DOCUMENT_UPDATE = 'DOCUMENT_UPDATE',
  DOCUMENT_DELETE = 'DOCUMENT_DELETE',
}
