export enum SocketType {
  CHAT_NOTIFICATION = 'chatNotification',
  EDIT_MESSAGE = 'editMessage',
  ERROR = 'error',
  JOIN_CHAT = 'joinChat',
  LEAVE_CHAT = 'leaveChat',
  SEND_MESSAGE = 'sendMessage',
  SIGN_OUT = 'signOut',
  REGISTER = 'register',
  RETRIEVE_MESSAGE = 'retrieveMessage',
  RESPONSE_MESSAGE = 'responseMessage',
  RESPONSE_RETRIEVE_MESSAGE = 'responseRetrieveMessage',
  RESPONSE_READ_MESSAGE = 'responseReadMessage',
  USER_ONLINES = 'onlineUsers',
}
